version: "3"
services:
  php:
    # імʼя контейнеру, яке будемо використовувати при вході на контейнер
    container_name: study_php_hw
    build:
      context: ./
      # посилання на докерфайл з налаштуванням контейнеру
      dockerfile: "docker/configs/php/Dockerfile"
    # встановлюємо змінні оточення
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    # прописуємо синхронізацію директорій
    volumes:
      - ./:/srv/src/study
    links:
      - db_mysql

  db_mysql:
    image: mysql:latest
    container_name: php_homework
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: php_homework
      MYSQL_USER: tars
      MYSQL_PASSWORD: tars
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d